apiVersion : extensions/v1beta1

kind : Deployment
metadata:
  name: cloudnativego
  labels:
    app : cloudnativego

spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app : cloudnativego
        tier : service
    spec:
      containers:
        - name: cloudnativego
          image: cloudnativego:1.0.1-alpine
          ports:
            - containerPort: 8080
          env:
             - name: PORT
               value: "8080"
          resources:
            requests:
              memory: "64Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
